sick_scan2: # configuration for sick_scan2_mrs_1xxx: For compatibility with ros versions previous to foxy, node and parameter name changed to sick_scan2 for all supported scanner. The type of scanner is configured by scanner_name only.
  ros__parameters:
    hostname : "192.168.0.1"
    frame_id : "cloud"
    imu_frame_id : "test"
    scanner_name : "sick_mrs_1xxx"
    port : 2112
    min_ang : -2.35619449
    max_ang : 2.35619449
