sick_scan2: # configuration for sick_scan2_lms_1xx: For compatibility with ros versions previous to foxy, node and parameter name changed to sick_scan2 for all supported scanner. The type of scanner is configured by scanner_name only.
  ros__parameters:
    hostname : "192.168.0.1"
    frame_id : "cloud"
    scanner_name : "sick_lms_1xx"
    port : 2112
    min_ang : -2.35619449
    max_ang : 2.35619449
